#
# Configuration
#
#
# Build Matrix
#

matrix:
  - os: linux
    dist: focal
    language: c

    compiler: gcc
    env: DESC="linux/gcc build and test"

    addons:
      apt:
        packages:
          - build-essential
          - cmake
          - net-tools
          - python3-pip
          - python3-setuptools
          - psmisc
      sonarcloud:
        organization: "l2dy-sonarcloud"
        token:
          secure: "kjsja+K2SMgEZwwjOrcWLGoDUiVhfs6o9ozsl8cisVcNU8hJv1xom8z15zuHBpkj25oDsPLI0zPLuwiaP6GTZfbEZ9w0R0N+m/ud2UbdlsMx/IQnFw+5Jm0vdWadVHZfdFPe1PguasGcBtfaCvSiDZud9J7+n1/dVJlt1iy62n6mJ1RHn/GWp0OKO3c/FbN2PAuPWZBPddoJ3qxeKZFpASGCso4SK+EDcF0nnyaFsU7pK3sRD0rO1X2nwDzPv2HElCNthlO4xnzFXShYqrGMqEi6GIfgulB2r+wpRv9Y+1K8POKR1vtJOsAH70ddfBvfceU3N17n2MdGtoQdpDwPnlV1LGuIY/s2RPDVVuDzzK0GtnP2RUdi//hvauBAx7Y9wyL5FuZmwoErQSSqWaNgjT93SNYVLp+sMzuppjyyWaXXNBqH5DNdh4ao4AVjKU1dNlZM0B7woNflMwUPLi1qyERwWMxtsgtu/XttktPUc/h2145jlgFakQgP0hUpXEf2zuf/I7WseUdToAP7huOvvFXRPyWQnT2OtQ3DHSxGGyPh4vrHj1eXyXBD6DRX457OvcW8e30AZo63kh/F8nqjH96WsQlDDV7X5gxZ+MJLy5jon5UB66vHqiXMoS4x+xgImDAXLKDNixndaNdrUheYk3zh/eCYgBVyx2Oz26iO/18=" # encrypted value of your token

    before_script:
      - cd ${TRAVIS_BUILD_DIR}
      - mkdir debug

    script:
      - cd debug
      - cmake ..
      - cd ..
      - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build debug/
      - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.cfamily.threads=2 -Dsonar.cfamily.cache.enabled=false
